#!/usr/bin/env bash  
export SPRING_R2DBC_USERNAME=$COFFEE_SOFTWARE_SHOW_DB_USERNAME
export SPRING_R2DBC_PASSWORD=$COFFEE_SOFTWARE_SHOW_DB_PASSWORD
export SPRING_R2DBC_URL=r2dbc:postgres://${COFFEE_SOFTWARE_SHOW_DB_HOST}/${COFFEE_SOFTWARE_SHOW_DB_NAME}
./gradlew bootRun