name: Deploy

env:
  GKE_CLUSTER: joshlong-com
  GKE_ZONE: us-central1-c
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

  COFFEE_SOFTWARE_SHOW_DB_HOST: ${{ secrets.COFFEE_SOFTWARE_SHOW_DB_HOST }}
  COFFEE_SOFTWARE_SHOW_DB_NAME: ${{ secrets.COFFEE_SOFTWARE_SHOW_DB_NAME }}
  COFFEE_SOFTWARE_SHOW_DB_PASSWORD: ${{ secrets.COFFEE_SOFTWARE_SHOW_DB_PASSWORD }}
  COFFEE_SOFTWARE_SHOW_DB_URL: ${{ secrets.COFFEE_SOFTWARE_SHOW_DB_URL }}
  COFFEE_SOFTWARE_SHOW_DB_USERNAME: ${{ secrets.COFFEE_SOFTWARE_SHOW_DB_USERNAME }}
  COFFEE_SOFTWARE_SHOW_YOUTUBE_DATA_API_KEY: ${{ secrets.COFFEE_SOFTWARE_SHOW_YOUTUBE_DATA_API_KEY }}
  COFFEE_SOFTWARE_SHOW_YOUTUBE_RABBITMQ_HOST : ${{ secrets.COFFEE_SOFTWARE_SHOW_YOUTUBE_RABBITMQ_HOST }}
  COFFEE_SOFTWARE_SHOW_YOUTUBE_RABBITMQ_PORT : ${{ secrets.COFFEE_SOFTWARE_SHOW_YOUTUBE_RABBITMQ_PORT }}
  COFFEE_SOFTWARE_SHOW_YOUTUBE_RABBITMQ_USERNAME : ${{ secrets.COFFEE_SOFTWARE_SHOW_YOUTUBE_RABBITMQ_USERNAME}}
  COFFEE_SOFTWARE_SHOW_YOUTUBE_RABBITMQ_PASSWORD : ${{ secrets.COFFEE_SOFTWARE_SHOW_YOUTUBE_RABBITMQ_PASSWORD }}
  COFFEE_SOFTWARE_SHOW_YOUTUBE_RABBITMQ_VIRTUAL_HOST : ${{ secrets.COFFEE_SOFTWARE_SHOW_YOUTUBE_RABBITMQ_VIRTUAL_HOST }}
  TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
  TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.GKE_CLUSTER  }}'
          location: '${{ env.GKE_ZONE }}'

      - run: |
          gcloud config set project $PROJECT_ID
          gcloud --quiet auth configure-docker
          kubectl get pods

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Deploy API
        run: |
          cd $GITHUB_WORKSPACE
          export ROOT_DIR=$GITHUB_WORKSPACE
          ./deploy/deploy.sh
